// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgl15S12vqf2MiWtmpZPBds5BX_nBJ3P4',
    appId: '1:479650638727:web:ee9a57c60970a302c24122',
    messagingSenderId: '479650638727',
    projectId: 'instagram-21e39',
    authDomain: 'instagram-21e39.firebaseapp.com',
    storageBucket: 'instagram-21e39.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIYCvM30jlOyvDteHL2Un78PZLVJiOYnY',
    appId: '1:479650638727:android:436e82ecc4af3389c24122',
    messagingSenderId: '479650638727',
    projectId: 'instagram-21e39',
    storageBucket: 'instagram-21e39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw_OzMPBiKyeOnazX5SvJzwLPPPC0_lq4',
    appId: '1:479650638727:ios:c151adc4a4de87abc24122',
    messagingSenderId: '479650638727',
    projectId: 'instagram-21e39',
    storageBucket: 'instagram-21e39.appspot.com',
    androidClientId: '479650638727-75mlsjd1cm0lqdjn6fjjouib02ia8lfc.apps.googleusercontent.com',
    iosClientId: '479650638727-9f9hv6m742324ouvm70kai2h8qj409lb.apps.googleusercontent.com',
    iosBundleId: 'com.chinjja.instagram',
  );
}
